SERPER_API_KEY=1180746159671cb4ffceed6cf2611fc0d1382473
OPENAI_API_KEY=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

